### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by RignonNoel** [Volontaria/API-Volontaria#257]
Volontaria official roadmap!

Since we don't have a lot of developers working in Volontaria at the moment, we will use this issue to track what next in this project.

Collaborations are welcome! If you want to start working on a feature that is listed below, please create another issue to start the discussion. This issue is only meant to be used as a placeholder.

Version 2.1:

- [ ] Admin panel to help administrator manage events and participations
- [x] Job posting system, to help find super contributor #254 
- [ ] Mobile app on Android and iOS

Next releases:

 - [ ] Bulk create events on admin panel #256 
 - [x] Import events to create from CSV file #255 
 - [ ] Integration with Zapier #252 
 - [ ] Integration of donation system #248
